### ISSUE TITLE
new_download

### ISSUE THREAD

**Issue by iamreza1381** [shabane/mp3tor2tel#18]
[[Magenta](magnet:?xt=urn:btih:1A6B5D57F649BDA9BB30D89EBADAD30AD3C4636A&dn=%5Bext.to%5D%20Tinker.Bell.and.the.Pirate.Fairy.2014.1080p.BluRay.x264.DTS-FGT&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce)](magnet:?xt=urn:btih:FB0B323D0F9E8DB6189DF328A24EDB5C767579E1&tr=udp%3A%2F%2Ftracker.bitsearch.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&dn=%5Bbitsearch.to%5D+Shrek.2.2004.1080p.BluRay.x264.DTS-FGT)
7929033545:AAECyBHvDMSEliuNpgPfhEwUm1DFSKJQce0
638786738

**Comment by shabane** [comment]
um the magnet that you add is in a url block of md,` []()` and this is wrong, it should be in plane text with not any additonal things

**Comment by shabane** [comment]
and i should also mention that files should be mp3 & less then 50MB each size!
